[package]
name = "ferrolex-ffi"
version = "0.2.0"
description = "Experimental C ABI spike for ferrolex"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
build = "build.rs"
publish = false

[lib]
crate-type = ["cdylib", "rlib", "staticlib"]

[features]
default = []
c-abi = []

[dependencies]
cbindgen = "0.29.4"
ferrolex-core = { path = "../ferrolex-core", version = "0.2.0" }
ferrolex-suggest = { path = "../ferrolex-suggest", version = "0.2.0" }

[build-dependencies]
cbindgen = "0.29.4"

[lints]
workspace = true
