[package]
name = "ferrolex-code"
version = "0.1.0"
description = "Source-code analysis for ferrolex"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
ferrolex-core = { path = "../ferrolex-core", version = "0.1.0" }
regex = "1.13.1"
unicode-normalization = "0.1.25"

[lints]
workspace = true
