[package]
name = "ferrolex-text"
version = "0.2.0"
description = "Plain-text analysis for ferrolex"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
ferrolex-core = { path = "../ferrolex-core", version = "0.2.0" }
unicode-normalization = "0.1.25"

[lints]
workspace = true
