/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Immutable checker backed by a word list or strict Hunspell import. */
export declare class Checker {
  /** Creates a checker from UTF-8, newline-delimited word-list text. */
  constructor(words: string)
  /**
   * Creates a checker by strictly importing caller-owned Hunspell files.
   *
   * # Errors
   *
   * Returns a JavaScript error when either file cannot be read or strict
   * import reports an unsupported or malformed recognition construct.
   */
  static fromHunspell(affPath: string, dicPath: string): Checker
  /**
   * Installs and strictly imports a digest-pinned catalog dictionary.
   *
   * Network, verification, and import work runs outside the JavaScript
   * event loop. The cache root is always selected by the caller.
   */
  static install(locale: string, cacheRoot: string): Promise<Checker>
  /** Returns whether this checker recognizes a word. */
  check(word: string): boolean
  /** Returns deterministic bounded spelling suggestions for a word. */
  suggest(word: string): Array<string>
}

/** Reviewed source metadata for one managed dictionary. */
export interface CatalogDictionary {
  /** Locale identifier accepted by `Checker.install`. */
  locale: string
  /** Pinned upstream revision. */
  revision: string
  /** Reviewed SPDX expression for the dictionary data. */
  license: string
  /** Immutable upstream license-notice URL. */
  licenseNoticeUrl: string
}

/** Returns the digest-pinned managed dictionary catalog. */
export declare function dictionaryCatalog(): Array<CatalogDictionary>
