/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Node.js spell checker backed by a word list, Hunspell dictionary, or
 * validated runtime artifact.
 */
export declare class SpellChecker {
  /**
   * Creates a spell checker from UTF-8, newline-delimited word-list text.
   *
   * Blank lines and lines whose first non-whitespace character is `#` are
   * ignored. Leading and trailing line whitespace is removed; internal
   * whitespace and inline `#` characters remain part of a word.
   */
  constructor(words: string, options?: CheckerOptions | undefined | null)
  /**
   * Creates a checker by strictly importing caller-owned Hunspell files.
   *
   * # Errors
   *
   * Returns a JavaScript error when either file cannot be read or strict
   * import reports an unsupported or malformed recognition construct.
   */
  static fromHunspell(affPath: string, dicPath: string, options?: CheckerOptions | undefined | null): SpellChecker
  /**
   * Loads a standalone, checksummed Hunspell runtime artifact from disk.
   *
   * The artifact carries its source provenance and runtime-semantics
   * version. Invalid, stale, truncated, or checksum-mismatched bytes are
   * returned as JavaScript errors rather than being silently accepted.
   *
   * # Errors
   *
   * Returns an error when the file cannot be read or the artifact fails
   * runtime-format, checksum, or provenance validation.
   */
  static fromRuntimeArtifact(path: string, options?: CheckerOptions | undefined | null): SpellChecker
  /**
   * Loads a standalone, checksummed Hunspell runtime artifact from bytes.
   *
   * # Errors
   *
   * Returns an error when the bytes fail runtime-format, checksum, or
   * provenance validation.
   */
  static fromRuntimeArtifactBytes(bytes: Buffer, options?: CheckerOptions | undefined | null): SpellChecker
  /**
   * Installs and strictly imports a digest-pinned catalog dictionary.
   *
   * Network, verification, and import work runs outside the JavaScript
   * event loop. The cache root is always selected by the caller.
   */
  static install(locale: string, cacheRoot: string, options?: CheckerOptions | undefined | null): Promise<SpellChecker>
  /** Returns whether this checker recognizes a word. */
  check(word: string): boolean
  /** Returns deterministic bounded spelling suggestions and completeness. */
  suggest(word: string, options?: SuggestionOptions | undefined | null): SuggestionResult
  /**
   * Adds one word to the live user-dictionary overlay.
   *
   * Returns whether the word was newly added. Blank lines, comment entries,
   * and entries containing line breaks are rejected with a JavaScript error.
   *
   * # Errors
   *
   * Returns an error when the word is empty, a comment entry, or cannot be
   * represented by the overlay's line-oriented persistence format.
   */
  addUserWord(word: string): boolean
  /**
   * Removes one word from the live user-dictionary overlay.
   *
   * # Errors
   *
   * Returns an error when the word is empty, a comment entry, or contains a
   * line break.
   */
  removeUserWord(word: string): boolean
  /** Returns the current user-dictionary words in deterministic order. */
  userWords(): Array<string>
}

/** Reviewed source metadata for one managed dictionary. */
export interface CatalogDictionary {
  /** Locale identifier accepted by `SpellChecker.install`. */
  locale: string
  /** Pinned upstream revision. */
  revision: string
  /** Reviewed SPDX expression for the dictionary data. */
  license: string
  /** Immutable upstream license-notice URL. */
  licenseNoticeUrl: string
}

/**
 * Construction options shared by word-list, Hunspell, and runtime-artifact
 * loaders.
 */
export interface CheckerOptions {
  /** Explicit Unicode normalization policy. Defaults to `exact`. */
  normalization?: NormalizationMode
}

/** Returns the digest-pinned managed dictionary catalog. */
export declare function dictionaryCatalog(): Array<CatalogDictionary>

/** Unicode normalization applied to word-list, query, and user-word input. */
export declare const enum NormalizationMode {
  /** Compare UTF-8 strings exactly as supplied. */
  Exact = 'exact',
  /** Canonically normalize Unicode text according to NFC. */
  Nfc = 'nfc',
  /** Compatibility-normalize Unicode text according to NFKC. */
  Nfkc = 'nfkc'
}

/** One ranked spelling suggestion. */
export interface Suggestion {
  /** Display spelling. */
  word: string
  /** OSA edit distance from the query, or zero for an explicit replacement. */
  distance: number
}

/** Completeness state for a bounded suggestion request. */
export declare const enum SuggestionCompleteness {
  /** Every candidate permitted by the configuration was considered. */
  Complete = 'complete',
  /** The configured candidate count was reached before the search completed. */
  CandidateLimitReached = 'candidateLimitReached',
  /** The configured edit-distance work budget was exhausted. */
  EditBudgetReached = 'editBudgetReached',
  /** The query exceeded the configured maximum length. */
  QueryTooLong = 'queryTooLong',
  /** A related seed exceeded the bounded normalization length. */
  RelatedSeedTooLong = 'relatedSeedTooLong'
}

/** Per-call bounds for deterministic suggestions. */
export interface SuggestionOptions {
  /** Maximum number of returned suggestions. Defaults to 8. */
  maxResults?: number
  /** Maximum OSA edit distance. Defaults to 2. */
  maxEditDistance?: number
  /** Maximum Unicode scalar values in a query or candidate. Defaults to 64. */
  maxWordScalars?: number
  /** Maximum source candidates inspected. Defaults to 100,000. */
  maxCandidates?: number
  /** Maximum dynamic-programming cells evaluated. Defaults to 1,000,000. */
  maxEditCells?: number
}

/** Bounded suggestion output and its completeness signal. */
export interface SuggestionResult {
  /** Suggestions in deterministic rank order. */
  suggestions: Array<Suggestion>
  /** Whether configured candidate and work limits were exhausted. */
  completeness: SuggestionCompleteness
}
