[package]
name = "ferrolex-core"
version = "0.2.0"
description = "Core dictionary interfaces for ferrolex"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dev-dependencies]
criterion = "0.5.1"
proptest = "=1.6.0"

[[bench]]
name = "lookup"
harness = false

[dependencies]
unicode-normalization = "0.1.25"
